import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/layout/footer';
import Navbar from '@/components/layout/nav';
import TrpcProvider from '@/components/Providers/TrpcProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Shopwise',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrpcProvider>
          <Navbar />
          {children}
          <Footer />
        </TrpcProvider>
      </body>
    </html>
  );
}
